title:  'M0blabs'
author: 'Kingm0b_'
name:  'Mais um blogzinho'

path: 'https://m0blabs.github.io'
url:  'https://m0blabs.github.io'

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md

safe: true
lsi: false

